"""test drop a nickname column to the user table

Revision ID: 83e4a332afd1
Revises: de3d6b348122
Create Date: 2024-01-22 09:12:43.287775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e4a332afd1'
down_revision = 'de3d6b348122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='simwire_plugin') as batch_op:
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='simwire_plugin') as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###
