name: indevelopme-simwire-plugin-elastic-beanstalk-github-actions-build

on:
  workflow_call:
  workflow_dispatch:
  push:
    ###########################################
    # stackoverflow credit:
    # https://stackoverflow.com/questions/57699839/
    ###########################################
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      # - '!main'   # excludes main
  pull_request:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  # name of job = "build"
  build:
    # the job runs on "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
      # checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # run docker-compose
      - name: Run Docker Compose
        run: |
          docker volume create --name=staticfiles
          docker-compose -f "docker-compose.yml" up -d --build


